stages:
  - build
  - archive

build_project:
  stage: build
  tags: [mac, x64, xcode]
  script:
    - cd Example
    - pod repo update
    - pod install
    - Pods/ObjectBox/setup.rb
    - xcodebuild build -workspace NotesExample.xcworkspace -scheme NotesExample-macOS -destination 'platform=OS X,arch=x86_64' -verbose

variables:
  GIT_SUBMODULE_STRATEGY: recursive